#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import dataclasses

from enum import Enum


class CustomCodeBase(Enum):
    """Custom state code base class"""

    @property
    def code(self) -> int:
        """Get Status Code"""
        return self.value[0]

    @property
    def msg(self) -> str:
        """Get Status Code Information"""
        return self.value[1]


class CustomResponseCode(CustomCodeBase):
    """Custom Response Status Code"""

    HTTP_200 = (200, 'Request successful')
    HTTP_201 = (201, 'New Request Successful')
    HTTP_202 = (202, 'Request accepted, but pending')
    HTTP_204 = (204, 'The request was successful but did not return the content')
    HTTP_400 = (400, 'Request error')
    HTTP_401 = (401, 'Unauthorized')
    HTTP_403 = (403, 'Ban Access')
    HTTP_404 = (404, 'No resources requested')
    HTTP_410 = (410, 'Resources requested have been permanently deleted')
    HTTP_422 = (422, 'The requested parameter is illegal')
    HTTP_425 = (425, 'The request could not be executed because the server could not meet the requirements')
    HTTP_429 = (429, 'Too many requests, server restrictions')
    HTTP_500 = (500, 'Internal server error')
    HTTP_502 = (502, 'Gateway Error')
    HTTP_503 = (503, 'The server is temporarily unable to process the request')
    HTTP_504 = (504, 'Gateway timeout')


class CustomErrorCode(CustomCodeBase):
    """Custom Error Status Code"""

    CAPTCHA_ERROR = (40001, 'Authentication code error')


@dataclasses.dataclass
class CustomResponse:
    """
    Provide an open response status code rather than an enumeration, which could be useful if you want to customize response information
    """

    code: int
    msg: str


class StandardResponseCode:
    """Standard Response Status Code"""

    """
    HTTP codes
    See HTTP Status Code Registry:
    https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

    And RFC 2324 - https://tools.ietf.org/html/rfc2324
    """
    HTTP_100 = 100  # CONTINUE:
    HTTP_101 = 101  # SWITCHING_PROTOCOLS: PROTOCOL SWITCH
    HTTP_102 = 102  # PROCESSING: PROCESSING
    HTTP_103 = 103  # EARLY_HINTS: HINT INFORMATION
    HTTP_200 = 200  # OK: REQUEST SUCCESSFUL
    HTTP_201 = 201  # CREATED: CREATED
    HTTP_202 = 202  # ACCEPTED: ACCEPTED
    HTTP_203 = 203  # NON_AUTHORITATIVE_INFORMATION: NON-AUTHORITATIVE INFORMATION
    HTTP_204 = 204  # NO_CONTENT: NO CONTENT
    HTTP_205 = 205  # RENET_CONTENT: RESET CONTENT
    HTTP_206 = 206  # PARTIAL_CONTENT: PARTLY
    HTTP_207 = 207  # MULTI_STATUS: MULTIPLE STATES
    HTTP_208 = 208  # ALREADY_REPORTED: REPORTED
    HTTP_226 = 226  # IM_USED: USED
    HTTP_300 = 300  # MULTIPLE_CHOICES: MULTIPLE CHOICES
    HTTP_301 = 301  # MOVED_PERMANENTLY: MOVING PERMANENTLY
    HTTP_302 = 302  # FOUND: TEMPORARY MOVEMENT
    HTTP_303 = 303  # SEE_OTHER: VIEW OTHER LOCATIONS
    HTTP_304 = 304  # NOT_MODIFIED: UNMODIFIED
    HTTP_305 = 305  # USE_PROXY: USE PROXY
    HTTP_307 = 307  # TEMPORARY_REDIRECT: TEMPORARY REORIENTATION
    HTTP_308 = 308  # PERMANENT_REDIRECT: REDIRECT PERMANENTLY
    HTTP_400 = 400  # BAD_REQUEST: REQUEST ERROR
    HTTP_401 = 401  # UNUTHORIZED: UNAUTHORIZED
    HTTP_402 = 402  # PAYMENT_REQUIRED: PAYMENT REQUIRED
    HTTP_403 = 403  # FORBIDDEN: ACCESS RESTRICTED
    HTTP_404 = 404  # NOT_FOUND: NOT FOUND
    HTTP_405 = 405  # METHOD_NOT_ALLOWED: METHOD NOT PERMITTED
    HTTP_406 = 406  # NOT_ACCEPTABLE: NOT ACCEPTABLE
    HTTP_407 = 407  # PROXY_AUTHENTICATION_REQUIRED: REQUIRES PROXY AUTHENTICATION
    HTTP_408 = 408  # REQUEST_TIMEOUT: REQUEST TIMEOUT
    HTTP_409 = 409  # CONFLICT: CONFLICT
    HTTP_410 = 410  # GONE: DELETED
    HTTP_411 = 411  # LANGTH_REQUIRED: NEED CONTENT LENGTH
    HTTP_412 = 412  # PROCONDITION_FAILED: PRECONDITIONS FAIL
    HTTP_413 = 413  # REQUEST_ENTITY_TOO_LARGE: REQUESTING ENTITY TOO LARGE
    HTTP_414 = 414  # REQUEST_URI_TOO_LONG: REQUEST URI TOO LONG
    HTTP_415 = 415  # UNSUPPORTTED_MEDIA_TYPE: UNSUPPORTED MEDIA TYPE
    HTTP_416 = 416  # REQUESD_RANGE_NOT_SATISFIABLE: THE REQUESTED RANGE DOES NOT MEET THE REQUIREMENTS
    HTTP_417 = 417  # EXPECTATION_FAILED: EXPECTING FAILURE
    HTTP_418 = 418  # UNSED: INACTIVE
    HTTP_421 = 421  # MISDIRECTED_REQUEST: MISDIRECTED REQUEST
    HTTP_422 = 422  # UNPROCESSABLE_CONTENT: ENTITIES UNABLE TO PROCESS
    HTTP_423 = 423  # LOCD: LOCKED
    HTTP_424 = 424  # FAILED_DEPENDENCY: DEPENDENCE FAILED
    HTTP_425 = 425  # TOO EARLY
    HTTP_426 = 426  # UPGRADE_REQUIRED: NEEDED UPGRADE
    HTTP_427 = 427  # UNASSIGN: UNDISTRIBUTED
    HTTP_428 = 428  # PROCONDITION_REQUIRED: PRECONDITIONS REQUIRED
    HTTP_429 = 429  # TOO_MANY_REQUESTS: TOO MANY REQUESTS
    HTTP_430 = 430  # Unassigned: Undistributed
    HTTP_431 = 431  # REQUEST_HEADER_FIELDS_TOO_LARGE: REQUEST HEADER FIELD IS TOO BIG
    HTTP_451 = 451  # UNVAILABLE_FOR_LEG_REASONS: NOT AVAILABLE FOR LEGAL REASONS
    HTTP_500 = 500  # INTERNAL_SERVER_ERRO: SERVER INTERNAL ERROR
    HTTP_501 = 501  # NOT_IMPLEMED: NOT ACHIEVED
    HTTP_502 = 502  # BAD_GATEWAY: WRONG GATEWAY
    HTTP_503 = 503  # SERVICE_UNAVAILABLE: NOT AVAILABLE
    HTTP_504 = 504  # GATEWAY_TIMEOUT: GATEWAY TIMEOUT
    HTTP_505 = 505  # HTTP_VERSION_NOT_SUPPORTED: HTTP VERSION NOT SUPPORTED
    HTTP_506 = 506  # VARIANT_ALSO_NEGOTIATES:
    HTTP_507 = 507  # INSUFFICIENT_STORAGE: INSUFFICIENT STORAGE SPACE
    HTTP_508 = 508  # LOOP_DETECTED: CYCLE DETECTED
    HTTP_509 = 509  # UNASSIGN: UNDISTRIBUTED
    HTTP_510 = 510  # NOT_EXTEND: UNEXTENDED
    HTTP_511 = 511  # NETWORK_AUTHENTICATION_REQUIRED: REQUIRES NETWORK AUTHENTICATION

    """
    WebSocket codes
    https://www.iana.org/assignments/websocket/websocket.xml#close-code-number
    https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
    """
    WS_1000 = 1000  # NORMAL_CLOSURE: NORMAL CLOSED
    WS_1001 = 1001  # GOING_AWAY: LEAVING
    WS_1002 = 1002  # PROTOCOL_ERRO: PROTOCOL ERROR
    WS_1003 = 1003  # UNSUPPOORD_DATA: UNSUPPORTED DATA TYPE
    WS_1005 = 1005  # NO_STATUS_RCVD: NOT RECEIVED
    WS_1006 = 1006  # ABNORMAL_CLOSURE: ABNORMALLY CLOSED
    WS_1007 = 1007  # INVALD_FRAME_PAYLOAD_DATA: INVALID FRAME LOAD DATA
    WS_1008 = 1008  # POLICY_VIOLATION: STRATEGIC INFRACTION
    WS_1009 = 1009  # MESSAGE_TO_BIG: TOO MUCH NEWS
    WS_1010 = 1010  # MANDATORY_EXT: REQUIRED EXTENSION
    WS_1011 = 1011  # INTERNAL_ERRO: INTERNAL ERROR
    WS_1012 = 1012  # SERVICE_RESTART: SERVICE RESTART
    WS_1013 = 1013  # TRY_AGAIN_LATER: PLEASE TRY AGAIN LATER
    WS_1014 = 1014  # BAD_GATEWAY: WRONG GATEWAY
    WS_1015 = 1015  # TLS_HANDSHAKE: TLS HANDSHAKE ERROR
    WS_3000 = 3000  # UNAUTHORIZED
    WS_3003 = 3003  # FORBIDDEN: ACCESS RESTRICTED
